In [1]:
import polars as pl

df = pl.DataFrame([["Alpha","Beta", "Gamma"],[1,2,3]],schema=["Letter", "Number"])
df

shape: (3, 2)
┌────────┬────────┐
│ Letter ┆ Number │
│ ---    ┆ ---    │
│ str    ┆ i64    │
╞════════╪════════╡
│ Alpha  ┆ 1      │
│ Beta   ┆ 2      │
│ Gamma  ┆ 3      │
└────────┴────────┘

In [2]:
df.write_ipc_stream("./test_data.ipc_stream")

In [3]:
df = pl.DataFrame([["Alpha","Beta", "Gamma", "Delta"],[1,2,3,4]],schema=["Letter", "Number"])
df

shape: (4, 2)
┌────────┬────────┐
│ Letter ┆ Number │
│ ---    ┆ ---    │
│ str    ┆ i64    │
╞════════╪════════╡
│ Alpha  ┆ 1      │
│ Beta   ┆ 2      │
│ Gamma  ┆ 3      │
│ Delta  ┆ 4      │
└────────┴────────┘

In [4]:
df.write_ipc_stream("./data.ipc_stream")